### ISSUE TITLE
 option to define width and height

### ISSUE THREAD

**Issue by SuperPutte** [aqt/webext-popup#11]
Can you add an option to define width and height of the popup-window in the settings?
If possible also site-specific.

**Comment by aqt** [comment]
I created two issues for these requests after reading your review: #7 and #8.

In the latest version of the extension (v1.3.1) you can now set a default width and height. I will be adding support for site-specific settings at a later time (but probably still this week) since it requires more work.

If you've not received the update yet you can try going to Addons, right-click the extension and pick Find updates.

**Comment by aqt** [comment]
Hi, I've implemented this and uploaded the new version to AMO.
It wil be visible once it has been reviewed and approved.
