### ISSUE TITLE
PopUp 1.3.2 data loss (e.g. history and session information) when the popped-up tab is closed

### ISSUE THREAD

**Issue by grahamperrin** [aqt/webext-popup#16]
After closure: 

- the tab is missing from the head of the list of recently closed tabs; and 
- if a tab to the same address is (re)opened, form input data that would otherwise have been saved is not present. 

I guess that loss may also occur if a crash (of the application) occurs whilst the tab is popped up. 

Side note: I have not attempted to make the form input data loss reproducible with a service worker-enabled PWA.

**Comment by aqt** [comment]
**Missing from recently closed tabs**
This is dependent on how Firefox handles windows of the popup type, and I think it might be expected behavior.

I _could_ probably work around the issue, by first restoring the popup to a regular window and then closing that window. Of course, that would _look_ fairly bad/buggy. I am uncertain though if the webextensions API allows "intercepting" the closing of the window so I can do this.

**Input data loss on closing window**
I'm not quite sure I understand this issue. I checked if the un-sent tweet was saved for a regular window since this case was not in your recording and it doesn't seem to be. Can you provide a recording of expected behavior?

Form/input data is not supposed to be kept when closing and re-opening a regular window/tab, presumably of privacy/security concerns. The page itself would need to save/restore that data as needed.

**Comment by aqt** [comment]
**Missing from recently closed tabs**
After further testing, the popup should show up in "Recently closed windows", since it is technically a window and no longer a tab.

**Comment by grahamperrin** [comment]
> … Recently closed windows …

Ah! I'm embarrassed that I didn't think of that. 

Unfortunately not working as expected with Waterfox, on this notebook … I might compare with Firefox. 

----

First, I must discover why the recently closed windows feature is simply not working, with my set of extensions, for a window that does _not_ originate with PopUp. Weirdness here! 

`browser.sessionstore.max_windows_undo` is `20` but I get nothing after closure of a window. I can't guess how long it's been like this because I go months without using the feature. Maybe an extensions conflict (if so, it'll be a rarity – apologies for the noise) …

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.31
$ pkg info firefox | grep Version
Version        : 60.0.1_3,1
$ date ; uname -v
Sat  2 Jun 2018 18:45:24 BST
FreeBSD 12.0-CURRENT #3 r334382: Thu May 31 01:37:12 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by grahamperrin** [comment]
>  I must discover why the recently closed windows feature is simply not working, with my set of extensions, for a window that does not originate with PopUp. 

https://redd.it/8o2e06 nothing conclusive there, yet. 

A screenshot of the symptom: 

![2018-06-02 23 27 14 popup 1 3 2 data loss e g history and session information when the popped-up tab is closed issue -16 aqt-webext-popup](https://user-images.githubusercontent.com/192271/40881394-5fcec440-66bd-11e8-818e-05b24a08d3d8.png)

– whilst the menu option is present and selectable (not greyed out), there is **no submenu**.

**Comment by grahamperrin** [comment]
Closing, not an issue with PopUp. If you like, label this issue as _invalid_. 

Explanation: https://www.reddit.com/comments/8o2e06/-/e06f6ml/

@aqt apologies for wasting your time here!

**Comment by aqt** [comment]
No worries
