### ISSUE TITLE
Command Line option? [ability to launch a page in app mode from a system shortcut]

### ISSUE THREAD

**Issue by allanlaal** [aqt/webext-popup#22]
use case:
I currently use Chrome to launch webapps in separate windows with no toolbars, so I can use them like normal apps.
sadly Chrome memfloods like crazy, so I want to switch these over to Firefox. 

your plugin already achieves the same webapp/popout view. is it somehow possible to specify it as a command line option when launching firefox?

**Comment by aqt** [comment]
It doesn't look possible. Webextensions can't read command line arguments and I can't find one that would pass a message to an addon. Because of this I'm closing this issue.

However,

I have previously denied a request to automatically open some domains as a popup automatically (#12). I have been wondering if that was the right decision and your feedback tipped the scale in favor of adding it.

Am I correct in that adding that feature would fulfill your request?

_Optionally if firefox is your main browser and you sometimes open these webapps not wanting a popup, you could create a new firefox profile and setup PopUp in it, and use the command line argument `-P "profilename"`._

**Comment by allanlaal** [comment]
I would recommend using full addresses with wildcard support instead of just domains
in that case: yes, it would fill my use case nicely :)

**Comment by aqt** [comment]
Absolutely, I've created #23 for that part
